repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-case-conflict
    -   id: end-of-file-fixer
-   repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.0.0
    hooks:
    -   id: hadolint
-   repo: https://github.com/markdownlint/markdownlint
    rev: d4722e89430631ab96cfb30719f163650b1d4b14
    hooks:
    -   id: markdownlint_docker
